# Generated by Django 4.2.2 on 2023-06-18 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_study_group_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='study_groups',
        ),
        migrations.RemoveField(
            model_name='study_group',
            name='user',
        ),
        migrations.AddField(
            model_name='study_group',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.school'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.school')),
                ('study_groups', models.ManyToManyField(to='main_app.study_group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
