# Generated by Django 4.2.2 on 2023-06-18 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_remove_school_study_groups_remove_study_group_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_groups',
        ),
        migrations.AddField(
            model_name='study_group',
            name='attending',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
