# Generated by Django 4.2.2 on 2023-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_profile_study_groups_study_group_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_group',
            name='description',
            field=models.TextField(default='--'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_group',
            name='name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
