# Generated by Django 4.2.2 on 2023-06-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_study_group_creator_alter_study_group_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_group',
            name='date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='study_group',
            name='time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
