# Generated by Django 4.2.2 on 2023-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_group',
            name='time',
            field=models.CharField(max_length=15),
        ),
    ]
