# fly.toml app configuration file generated for frosty-paper-254 on 2023-06-22T13:29:55-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-paper-254"
primary_region = "den"
console_command = "/code/manage.py shell"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/code/staticfiles"
  url_prefix = "/static"
